# Generated by Django 5.2.17 on 2026-09-30 00:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Maquinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('categoria', models.CharField(max_length=100)),
                ('tarifa_diaria', models.DecimalField(decimal_places=0, max_digits=10)),
                ('garantia_fija', models.DecimalField(decimal_places=0, max_digits=10)),
                ('stock_disponible', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='CarroArriendo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carro', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente de Pago'), ('PAGADO', 'Pagado (Stock Descontado)'), ('ENTREGADO', 'Equipo Entregado al Cliente'), ('COMPLETADO', 'Devuelto (Stock Reincorporado)'), ('CANCELADO', 'Cancelado (Stock Liberado)')], default='PENDIENTE', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('total_pagar', models.DecimalField(decimal_places=0, default=0, max_digits=12)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='app.carroarriendo')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.maquinaria')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleContrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('precio_congelado', models.DecimalField(decimal_places=0, max_digits=12)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app.contrato')),
                ('maquinaria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.maquinaria')),
            ],
        ),
    ]
