# Generated by Django 5.2.17 on 2026-09-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='imagen_url',
            field=models.URLField(blank=True, default='https://via.placeholder.com/400x300?text=Sin+Imagen', max_length=800, null=True),
        ),
    ]
