# Generated by Django 5.2.17 on 2026-09-30 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_maquinaria_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='maquinaria',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
