# Generated by Django 5.2.17 on 2026-09-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_maquinaria_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallecontrato',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='itemcarro',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
